name: SonarQube
on:
  push:
    branches: [ dev ]
jobs:
  sonarQubeTrigger:
    name: "SonarQube Trigger"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v1.4
        with:
           projectBaseDir: .
           projectKey: "Selinux24_Skirmish_dev"
           orgnization: "selinux24-github"
